language: csharp
solution: SwiftPbo.sln
script:
  - sudo apt-get install nunit-console
  - sed -i 's/<SignAssembly>true<\/SignAssembly>/<SignAssembly>false<\/SignAssembly>/g' SwiftPbo/SwiftPbo.csproj
  - nuget restore SwiftPbo.sln
  - xbuild /p:Configuration=Debug SwiftPbo.sln
  - nunit-console SwiftPbo.Tests/bin/Debug/SwiftPbo.Tests.dll