language: csharp
solution: SwiftPbo.sln
before_install:
  - sudo apt-get install nunit-console
before_script:
  - nuget restore SwiftPbo.sln
after_script:
  - nunit-console SwiftPbo.Tests\bin\Debug\SwiftPbo.Tests.dll